// ===== TEXTOS DE LA PÁGINA, EN ESPAÑOL E INGLÉS =====
//
// Cómo funciona: en index.html cada elemento con texto lleva data-t="clave".
// main.js busca la clave aquí y escribe el texto del idioma elegido.
// Para cambiar una frase, se cambia aquí y en los dos idiomas. No se toca el HTML.
//
// Si una clave vale "" en un idioma, el elemento se oculta en ese idioma
// (se usa para el aviso de que las demos están en español).

const TEXTOS = {
  es: {
    "doc.titulo": "Juan Diego Guio · Webs y automatizaciones para negocios",
    "doc.descripcion": "Webs para bares, restaurantes y comercios, automatizaciones con Excel y soporte informático. Oviedo y en remoto.",

    "saltar": "Ir al contenido",
    "nav.aria": "Secciones",
    "nav.servicios": "Servicios",
    "nav.proyectos": "Proyectos",
    "nav.soporte": "Soporte",
    "nav.contacto": "Contacto",
    "idioma.aria": "Idioma",
    "idioma.es": "Español",
    "idioma.en": "Inglés",

    "portada.h1": "Webs y automatizaciones para negocios que no tienen tiempo para la informática",
    "portada.entradilla": "Monto la web de tu bar, tienda o negocio, automatizo las tareas que haces a mano con Excel y te resuelvo los problemas del ordenador. Trabajo con inteligencia artificial, así que entrego rápido y con precio cerrado antes de empezar.",
    "portada.cta1": "Pedir presupuesto",
    "portada.cta2": "Ver proyectos",
    "portada.lugar": "Oviedo, Asturias · también en remoto",

    "comanda.aria": "Comanda con los tres servicios",
    "comanda.cab": "COMANDA",
    "comanda.mesa": "MESA 01",
    "comanda.l1": "Web para tu negocio",
    "comanda.l1s": "carta, horario, reservas",
    "comanda.l2": "Automatización",
    "comanda.l2s": "adiós al copiar y pegar",
    "comanda.l3": "Soporte informático",
    "comanda.l3s": "PC, correo, impresoras",
    "comanda.nota": "Nota: precio cerrado, sin sorpresas",
    "comanda.pie": "*** MARCHANDO ***",

    "servicios.h2": "Servicios",
    "s1.h3": "Webs para negocios locales",
    "s1.p": "Una web que responde a lo que pregunta tu cliente antes de venir: qué ofreces, cuánto cuesta, si estás abierto y cómo reservar o contactar.",
    "s1.li1": "Se ve bien en el móvil, que es desde donde te buscan",
    "s1.li2": "Reservas o pedidos que te llegan por WhatsApp o correo",
    "s1.li3": "Cambias precios y horarios tú mismo, o te lo cambio yo",
    "s1.li4": "Publicada con tu dominio",
    "s2.h3": "Automatizaciones",
    "s2.p": "Si cada semana o cada mes copias datos de un sitio a otro, eso se puede hacer solo.",
    "s2.li1": "Juntar varios Excel en un informe",
    "s2.li2": "Resúmenes de gastos, ventas o stock",
    "s2.li3": "Avisos por correo cuando algo cambia",
    "s2.li4": "Pequeñas herramientas a medida, como calculadoras de costes",
    "s3.h3": "Soporte informático",
    "s3.p": "El ordenador que va lento, la impresora que no imprime, el correo que no llega.",
    "s3.li1": "Instalar y configurar Windows y programas",
    "s3.li2": "Correo, Office y copias de seguridad",
    "s3.li3": "Resolver errores y dejarlo explicado",
    "s3.li4": "En Oviedo en persona, o en remoto",

    "proyectos.h2": "Proyectos",
    "proyectos.intro": "Proyectos de demostración, pensados para problemas reales de la hostelería, que es el sector que conozco desde dentro. Puedes probarlos y ver el código.",
    "proyectos.idioma": "",
    "comun.codigo": "Ver el código",

    "p1.h3": "Web para una sidrería",
    "p1.p": "Carta por secciones con los platos ilustrados, horario y un indicador de abierto o cerrado que usa la hora de Oviedo. Las reservas solo ofrecen horas en las que el local abre y llegan por WhatsApp ya escritas.",
    "p1.tecnica": "HTML, CSS y JavaScript sin librerías",
    "p1.ver": "Ver la web",
    "ms.estado": "Abierto ahora · cierra a las 23:30",
    "ms.titulo": "Sidra escanciada y cocina de casa",
    "ms.l1": "Fabada asturiana",
    "ms.l2": "Cachopo de ternera",
    "ms.boton": "Reservar mesa",

    "p2.h3": "Calculadora de escandallos",
    "p2.p": "Calcula el coste real de cada ración, con las mermas de limpiar y cocinar, y el precio al que hay que venderla. Si escribes el precio de tu carta, te dice si estás perdiendo margen.",
    "p2.tecnica": "JavaScript sin librerías · guarda recetas en el navegador · exporta a Excel",
    "p2.ver": "Probar la calculadora",
    "me.coste": "Coste por ración",
    "me.pvp": "Precio recomendado",
    "me.aviso": "A 18 € en carta: food cost del 36,9 %",

    "p3.h3": "Resumen mensual de gastos",
    "p3.p": "Un script que junta las facturas de todos los proveedores en Excel y saca el informe del mes: cuánto se ha gastado, con quién, en qué y qué productos han subido de precio.",
    "p3.tecnica": "Python solo con la librería estándar · lee Excel sin instalar nada",
    "p3.ver": "Ver un informe de ejemplo",
    "mg.carne": "Carne",
    "mg.bebida": "Bebida",
    "mg.pescado": "Pescado",
    "mg.sube": "Lechuga +12,2 %",

    "proceso.h2": "Cómo trabajo",
    "paso1.h3": "Me cuentas qué necesitas",
    "paso1.p": "Por WhatsApp, correo o en persona si estás en Oviedo. Sin tecnicismos.",
    "paso2.h3": "Te paso un presupuesto cerrado",
    "paso2.p": "Qué incluye, cuánto cuesta y cuándo está. Si cambia algo, lo hablamos antes.",
    "paso3.h3": "Ves una primera versión",
    "paso3.p": "Pronto, para corregir sobre algo real y no sobre una idea.",
    "paso4.h3": "Te lo entrego funcionando",
    "paso4.p": "Publicado, probado y explicado para que lo puedas usar sin depender de mí.",

    "sobre.h2": "Sobre mí",
    "sobre.p1": "Soy Juan Diego, tengo 19 años y vivo en Oviedo. Trabajo en la cocina de un club de tenis y estudio Desarrollo de Aplicaciones Multiplataforma.",
    "sobre.p2": "Lo que más se me da es entender un problema y buscar cómo resolverlo. Uso la inteligencia artificial como herramienta de trabajo, y eso me permite entregar en días lo que antes llevaba semanas.",
    "sobre.p3": "Conozco la hostelería desde dentro: sé lo que es un servicio a tope, lo que cuesta un plato y por qué el dueño de un bar no tiene tiempo para pelearse con el ordenador.",

    "contacto.h2": "Hablemos",
    "contacto.p": "Cuéntame qué necesitas y te respondo con un presupuesto cerrado.",
    "contacto.correo": "Correo",
    "contacto.copiar": "Copiar correo",
    "contacto.whatsapp": "WhatsApp",
    "contacto.escribir": "Escribir por WhatsApp",
    "contacto.copiado": "Correo copiado. Pégalo en tu programa de correo.",
    "contacto.copiado_manual": "Correo seleccionado: cópialo con Ctrl+C.",
    "contacto.mensaje": "Hola Juan Diego, he visto tu web y quería pedirte presupuesto para…",

    "pie.lugar": "Oviedo, Asturias",
  },

  en: {
    "doc.titulo": "Juan Diego Guio · Websites and automation for small businesses",
    "doc.descripcion": "Websites for bars, restaurants and shops, Excel automation and IT support. Based in Oviedo, Spain. Remote work worldwide.",

    "saltar": "Skip to content",
    "nav.aria": "Sections",
    "nav.servicios": "Services",
    "nav.proyectos": "Projects",
    "nav.soporte": "IT support",
    "nav.contacto": "Contact",
    "idioma.aria": "Language",
    "idioma.es": "Spanish",
    "idioma.en": "English",

    "portada.h1": "Websites and automation for business owners with no time for computers",
    "portada.entradilla": "I build the website for your bar, shop or small business, automate the jobs you now do by hand in Excel, and fix the computer problems that slow you down. I work with AI, so you get it fast and at a fixed price agreed before I start.",
    "portada.cta1": "Get a quote",
    "portada.cta2": "See my work",
    "portada.lugar": "Oviedo, Spain · remote work worldwide",

    "comanda.aria": "Kitchen order ticket listing the three services",
    "comanda.cab": "ORDER",
    "comanda.mesa": "TABLE 01",
    "comanda.l1": "A website for your business",
    "comanda.l1s": "menu, opening hours, bookings",
    "comanda.l2": "Automation",
    "comanda.l2s": "no more copy and paste",
    "comanda.l3": "IT support",
    "comanda.l3s": "PCs, email, printers",
    "comanda.nota": "Note: fixed price, no surprises",
    "comanda.pie": "*** ON IT ***",

    "servicios.h2": "Services",
    "s1.h3": "Websites for local businesses",
    "s1.p": "A website that answers what your customer wants to know before they come: what you offer, what it costs, whether you are open, and how to book or get in touch.",
    "s1.li1": "Looks right on a phone, which is where people find you",
    "s1.li2": "Bookings and orders that reach you by WhatsApp or email",
    "s1.li3": "You change prices and hours yourself, or I do it for you",
    "s1.li4": "Published on your own domain",
    "s2.h3": "Automation",
    "s2.p": "If every week or every month you copy data from one place to another, that can run on its own.",
    "s2.li1": "Merging several Excel files into one report",
    "s2.li2": "Summaries of spending, sales or stock",
    "s2.li3": "Email alerts when something changes",
    "s2.li4": "Small custom tools, such as cost calculators",
    "s3.h3": "IT support",
    "s3.p": "The computer that crawls, the printer that will not print, the email that never arrives.",
    "s3.li1": "Installing and setting up Windows and software",
    "s3.li2": "Email, Office and backups",
    "s3.li3": "Fixing errors and writing down what was wrong",
    "s3.li4": "In person in Oviedo, or remotely",

    "proyectos.h2": "Projects",
    "proyectos.intro": "Demo projects built around real problems in hospitality, the trade I know from the inside. You can try them and read the code.",
    "proyectos.idioma": "The demos themselves are in Spanish, since they are built for businesses in Asturias. The code and the comments are in Spanish too.",
    "comun.codigo": "View the code",

    "p1.h3": "Website for a cider house",
    "p1.p": "An illustrated menu by section, opening hours, and an open-or-closed indicator that uses the local time in Oviedo. The booking form only offers times when the place is actually open, and the booking arrives on WhatsApp ready written.",
    "p1.tecnica": "HTML, CSS and JavaScript, no libraries",
    "p1.ver": "Open the site",
    "ms.estado": "Open now · closes at 23:30",
    "ms.titulo": "Poured cider and home cooking",
    "ms.l1": "Asturian bean stew",
    "ms.l2": "Breaded veal cachopo",
    "ms.boton": "Book a table",

    "p2.h3": "Food cost calculator",
    "p2.p": "Works out what a portion really costs, including the weight lost in trimming and cooking, and the price it has to sell for. Type the price on your menu and it tells you whether you are losing margin.",
    "p2.tecnica": "JavaScript, no libraries · saves recipes in the browser · exports to Excel",
    "p2.ver": "Try the calculator",
    "me.coste": "Cost per portion",
    "me.pvp": "Recommended price",
    "me.aviso": "At €18 on the menu: 36.9 % food cost",

    "p3.h3": "Monthly spending report",
    "p3.p": "A script that merges every supplier invoice in Excel and produces the month's report: how much was spent, with whom, on what, and which products went up in price.",
    "p3.tecnica": "Python, standard library only · reads Excel with nothing to install",
    "p3.ver": "See a sample report",
    "mg.carne": "Meat",
    "mg.bebida": "Drinks",
    "mg.pescado": "Fish",
    "mg.sube": "Lettuce +12.2 %",

    "proceso.h2": "How I work",
    "paso1.h3": "You tell me what you need",
    "paso1.p": "By WhatsApp, email, or face to face if you are in Oviedo. No jargon.",
    "paso2.h3": "I send you a fixed quote",
    "paso2.p": "What it includes, what it costs and when it is ready. If anything changes, we talk about it first.",
    "paso3.h3": "You see a first version early",
    "paso3.p": "Early on, so we correct something real instead of an idea.",
    "paso4.h3": "I hand it over working",
    "paso4.p": "Published, tested and explained, so you can use it without depending on me.",

    "sobre.h2": "About me",
    "sobre.p1": "I am Juan Diego, I am 19 and I live in Oviedo, in the north of Spain. I work in the kitchen of a tennis club and I am studying software development.",
    "sobre.p2": "What I am best at is understanding a problem and working out how to solve it. I use AI as a working tool, and that lets me deliver in days what used to take weeks.",
    "sobre.p3": "I know hospitality from the inside: I know what a full service feels like, what a dish costs, and why the owner of a bar has no time to fight with a computer.",

    "contacto.h2": "Let's talk",
    "contacto.p": "Tell me what you need and I will come back with a fixed price.",
    "contacto.correo": "Email",
    "contacto.copiar": "Copy email",
    "contacto.whatsapp": "WhatsApp",
    "contacto.escribir": "Message me on WhatsApp",
    "contacto.copiado": "Email copied. Paste it into your mail app.",
    "contacto.copiado_manual": "Email selected: copy it with Ctrl+C.",
    "contacto.mensaje": "Hi Juan Diego, I saw your website and I would like a quote for…",

    "pie.lugar": "Oviedo, Spain",
  },
};
